### ISSUE TITLE
odd years aren't scraped

### ISSUE THREAD

**Issue by zcei** [yannickoo/klubnacht#16]
Only January is scraped, rest missing

**Comment by zcei** [comment]
There is a tracking whether we are in December each time we leave the month loop.
So we're always in December, thus it's always executed.

In the block we increment `i` to push the first month of the next year.
Afterwards the loop starts over again, so `i` is incremented again. This is why all other month of odd years are left out.

https://github.com/yannickoo/klubnacht/blob/master/berghainScraper.js#L89-L99

**Comment by zcei** [comment]
Still not f1xed

**Comment by tonekk** [comment]
Can confirm, :+1: for urgent fix

**Comment by yannickoo** [comment]
fixed in #17
